[package]
name = "we_ball_sc"
version = "1.0.0"
authors = []

[addresses]
admin = "0cc00fe367a4f9e47b7252c98b3245db3dfb27aea30e5680dc557ebf5aab1a20"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
